---
- hosts: srv
  become: true
  gather_facts: no
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
  tasks:
  - name: Copying ssh key
    copy:
     src: ../id_rsa
     dest: /home/ubuntu/.ssh/id_rsa
     mode: 0400
     owner: ubuntu
  - name: Installing aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
  - name: Installing required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: ['ca-certificates', 'curl', 'gnupg', 'python3-pip', 'git'] 
  - name: Adding Docker GPG apt Key
    apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present
  - name: Adding Docker Repository
    apt_repository:
     repo: deb https://download.docker.com/linux/ubuntu focal stable
     state: present
  - name: Updating apt and installing docker
    apt: name={{ item }} state=latest update_cache=yes
    loop: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin', 'docker-compose'] 
  - name: Creating a directory for kubespray if it does not exist
    file:
     path: /home/ubuntu/kubespray
     state: directory
     mode: '0755'
  - name: Cloning 2.19 release of Kubespray
    git:
     repo: https://github.com/kubernetes-sigs/kubespray
     dest: /home/ubuntu/kubespray
     version: release-2.19
  - name: Installing specified python requirements for kubespray
    pip:
     requirements: /home/ubuntu/kubespray/requirements.txt
  - name: Copying sample inventory directory as mycluster
    command: cp -r /home/ubuntu/kubespray/inventory/sample /home/ubuntu/kubespray/inventory/mycluster
  - name: Copying terrafom-generated inventory file to kubespray
    copy:
     src: ../k8s_inventory.ini
     dest: /home/ubuntu/kubespray/inventory/mycluster/inventory.ini
  - name: Change flags to kubespray folder
    command: chmod -R 777 kubespray
  - name: Deploying Kubernates cluster
    command: ansible-playbook -i /home/ubuntu/kubespray/inventory/mycluster/inventory.ini -u ubuntu --become --become-user=root /home/ubuntu/kubespray/cluster.yml --private-key=/home/ubuntu/.ssh/id_rsa
  - name: Copying ansible inventory
    copy:
     src: ../inventory.ini
     dest: /home/ubuntu/inventory.ini
     owner: ubuntu
  - name: Copying Ingress deployment
    copy:
     src: ingress-controller-deploy.yaml
     dest: /home/ubuntu/ingress-controller-deploy.yaml
     owner: ubuntu
  - name: Copying ansible playbook
    copy:
     src: internal_ansible_playbook.yaml
     dest: /home/ubuntu/ansible_playbook.yaml
     owner: ubuntu
  - name: Kube-master provisioning
    command: ansible-playbook -i /home/ubuntu/inventory.ini -u ubuntu --become --become-user=root /home/ubuntu/ansible_playbook.yaml --private-key=/home/ubuntu/.ssh/id_rsa